<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
  <Reference Include="tyuiu.courses.programming.interfaces">
    <HintPath>..\Tyuiu.Courses.Programming.Interfaces.dll</HintPath>
  </Reference>
</ItemGroup>

</Project>
